# Deployment objects is pretty much the same as replica sets with extra features
# An entity in kubernetes that manages the replica set for you
# Basically the same as replica set object but it does automatic rolling updates
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: springboot
  replicas: 2
  template: # template for the pods - pod definitions
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - name: app
        image: innoirvingdev/hello-springboot:6.0
        imagePullPolicy: Always

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: nodejs
  replicas: 2
  template: # template for the pods - pod definitions
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: app
        image: innoirvingdev/hello-node:6.0
        imagePullPolicy: Always