# Discovery + Loadbalancing

apiVersion: v1
kind: Service
metadata:
  name: springboot
spec:
  # Defines which pod are going to be represented by this service
  selector:
    app: springboot
  # Define which ports u are exposing for this service
  # it means it is going to accept traffic at port 80
  # and forwards traffic to 8080 for pods
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080 # Only used for NodePort, anything greater than 30000
                    # 30080
  type: NodePort # Expose a port through the (Node) Virtual machine
  # type: ClusterIP # will only be accessible in the internal cluster - private services

---

# Discovery + Loadbalancing

apiVersion: v1
kind: Service
metadata:
  name: nodejs
spec:
  # Defines which pod are going to be represented by this service
  selector:
    app: nodejs
  # Define which ports u are exposing for this service
  # it means it is going to accept traffic at port 80
  # and forwards traffic to 8080 for pods
  ports:
  - name: http
    port: 3000
    targetPort: 8080
    nodePort: 30081 # Only used for NodePort, anything greater than 30000
                    # 30080
  type: NodePort # Expose a port through the (Node) Virtual machine

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: queue
# spec:
#   selector:
#     app: queue
#     version: "0"
#   ports:
#   - name: http
#     port: 8161
#     nodePort: 30010
#   type: NodePort