# Deployment objects is pretty much the same as replica sets with extra features
# An entity in kubernetes that manages the replica set for you
# Basically the same as replica set object but it does automatic rolling updates
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name | default .Release.Name }}-green
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: {{ .Values.replicas }}
  template: # template for the pods - pod definitions
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: green
    spec:
      containers:
      - name: app
        image: innoirvingdev/hello-nodejs:green
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        # Lets cluster manager know a pod is able to run on a node or not
        resources:
          requests:
            cpu: 20m # m - millicores
                     # M - megacores

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name | default .Release.Name }}-blue
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  replicas: {{ .Values.replicas }}
  template: # template for the pods - pod definitions
    metadata:
      labels:
        app: {{ .Values.app.name }}
        version: green
    spec:
      containers:
        - name: app
          image: innoirvingdev/hello-nodejs:blue
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          # Lets cluster manager know a pod is able to run on a node or not
          resources:
            requests:
              cpu: 20m # m - millicores
              # M - megacores